<script src="{{ url('assets/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url('assets/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
<script src="{{ url('assets/js/ruang-admin.min.js') }}"></script>
<script src="{{ url('assets/vendor/chart.js/Chart.min.js') }}"></script>
<script src="{{ url('assets/js/demo/chart-area-demo.js') }}"></script>
<script src="{{ url('assets/vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url('assets/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>